# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_plateform.antispam:
        class: OCPlateformBundle\Antispam\OCAntispam
        arguments: ["@mailer", %locale%, 50]

    oc_platform.doctrine.notification:
        class: OCPlateformBundle\DoctrineListener\ApplicationNotification
        arguments: ["@mailer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }